library(trackdown)
update_file(file="/home/geordan/Desktop/R/R md/Assignment.Rmd", gfile= "Assignment.Rmd", gpath = "Assignment")
download_file(file="/home/geordan/Desktop/R/R md/Assignment.Rmd", gfile= "Assignment.Rmd", gpath = "Assignment")
upload_file(file="/home/geordan/Desktop/R/R md/Assignment.Rmd", gfile= "Assignment.Rmd", gpath = "Assignment")
render_file(file="/home/geordan/Desktop/R/R md/Assignment.Rmd", gfile= "Assignment.Rmd", gpath = "Assignment")
